name: reactBuild
on:
  push:
    branches: [main]
jobs:
  build-deploy-reactapp:
    runs-on: ubuntu-latest
    concurrency:
        group: dp
        cancel-in-progress: true
    steps:
      - name: checkout actons
        uses: actions/checkout@v6.0.2
      - name: setup nodejs
        uses: actions/checkout@v6.0.2
        with:
          node-version: "lts/*"
          cache: 'npm'
      - name: install deps
        run: npm install
      - name: react build
        run: npm run build
      - name: deploy
        run: npm run deploy
      - name: upload artifacts
        uses: actions/upload-artifact@v7.0.1
        with:
          name: reactBuild
          path: dist/
          

          
        
        
